import Head from "next/head";
import Image from "next/image";
// import icons
import { BsFillMoonStarsFill } from "react-icons/bs";

export default function Home() {
  return (
    <>
      <Head>
        <title>Porfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;800&display=swap');
        </style>
      </Head>
      <div>
        <main className="font-poppins bg-blue-50 min-h-screen px-10">
          {/* nav and hero */}
          <section>
            {/* nav */}
            <nav className="py-10 flex justify-between">
              <h1 className="text-sm">Developed by Bhanuka Kavishka</h1>
              <ul className="flex items-center">
                {/* icon */}
                <li>
                  <BsFillMoonStarsFill className="cursor-pointer text-xl mx-10" />
                </li>
                <li>
                  <a href="https://drive.google.com/file/d/1REqBXTsnBiq46O5dYndOvA8dxy-MWtWP/view?usp=sharing" 
                  className=" bg-blue-400 text-black px-4 py-2 border-none rounded-md"
                  download={"Resume"}>
                    Resume
                  </a>
                </li>
              </ul>
            </nav>
          </section>
        </main>
      </div>
    </>
  );
}
