import Head from "next/head";
import Image from "next/image";

//import images
import profileImage from "../public/pro.png";
// import icons
import { BsFillMoonStarsFill } from "react-icons/bs";
import { FaGithub } from "react-icons/fa6";
import { FaLinkedin } from "react-icons/fa";
import { SiGmail } from "react-icons/si";

export default function Home() {
  return (
    <>
      <Head>
        <title>Porfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;800&display=swap');
        </style>
      </Head>
      <div>
        <main className="font-poppins bg-blue-50 min-h-screen px-10">
          {/* nav and hero */}
          <section>
            {/* nav */}
            <nav className="py-10 flex justify-between">
              <h1 className="text-sm text-blue-400">Developed by Bhanuka Ariyarathne</h1>
              <ul className="flex items-center">
                {/* icon */}
                <li>
                  <BsFillMoonStarsFill className="cursor-pointer text-xl mx-10" />
                </li>
                <li>
                  <a href="https://drive.google.com/file/d/1REqBXTsnBiq46O5dYndOvA8dxy-MWtWP/view?usp=sharing" 
                  className=" bg-blue-400 text-black px-4 py-2 border-none rounded-md"
                  download={"Resume"}>
                    Resume
                  </a>
                </li>
              </ul>
            </nav>
            {/* hero */}
            <div className="text-center p-10">
              <h1 className=" text-5xl font-bold text-blue-400">Bhanuka Ariyarathne</h1>
              <h3 className=" text-2xl py-4">UNDERGRADUATE | BACHELOR OF INFORMATIONTECHNOLOGY </h3>
              <p className="text-sm py-4 text-gray-400 leading-6">A final year proactive Bachelor of Information Technology (External) student at the University of Colombo School of Computing. Possess strong communication skills with fluency in English and Sinhala. Keen to pursue a career in professional services with a focus on IT and software development roles.</p>
            </div>
            {/* social icons */}
            <div className="text-5xl flex justify-center gap-16 text-gray-500">
            <a href="https://github.com/Bhanuka99"><FaGithub /></a>
            <a href="https://linkedin.com/in/bhanuka-ariyarathne"><FaLinkedin /></a>
            <a href="mailto:bhanuka.ariyarathne@gmail.com"><SiGmail /></a>
            </div>
            {/* profile */}
            <div className="m-auto relative bg-gradient-to-b from-blue-200 w-80 h-80 p-5 mt-20 rounded-full">
              <Image src={profileImage} alt="profile pic" layout="" objectFit="cover"/>
            </div>
          </section>
        </main>
      </div>
    </>
  );
}
